shop_moves_download_homepage:
    path:     /
    defaults: { _controller: ShopMovesDownloadBundle:Default:index }
shop_moves_download_image_start:
    path:     /image-downloader
    defaults: { _controller: ShopMovesWebInterfaceBundle:UnasMigration:downloadImages }

